### ISSUE TITLE
Settings incorrectly scoped when prefix matches valid name

### ISSUE THREAD

**Issue by nk9** [nk9/just_sublime#15]
`set export` is a valid setting, but `set exported` is not. Yet the first part of the latter is incorrectly scoped:

<img width="208" alt="image" src="https://user-images.githubusercontent.com/3646730/234125654-97c514a1-af7a-44b0-b1f2-d4c081057a58.png">

**Comment by nk9** [comment]
It looks like the issue is the way variables are used in the matches:

```yaml
variables:
  boolean_settings: |
    (?x)
      allow-duplicate-recipes | dotenv-load | export | fallback | ignore-comments |
      positional-arguments | windows-powershell

contexts:
  settings-boolean:
    - match: '\b{{boolean_settings}}\b'
      scope: entity.name.definition.just
      push:
        - constant-boolean
        - assignment-operator
    - include: else-pop
```

Those word break anchors (`\b`), although [correct Oniguruma](https://github.com/kkos/oniguruma/blob/master/doc/RE), are for some reason not applying.

I have tried this instead, [based on the CSS syntax](https://github.com/sublimehq/Packages/blob/master/CSS/CSS.sublime-syntax):

```yaml
variables:
  break: (?=[[^-_[:alnum:]\\]&&[[:ascii:]]]|\Z)

  boolean_settings: |
    \b(?x:
      allow-duplicate-recipes | dotenv-load | export | fallback | ignore-comments |
      positional-arguments | windows-powershell
    ){{break}}

contexts:
  settings-boolean:
    - match: '{{boolean_settings}}'
      scope: entity.name.definition.just
      push:
        - constant-boolean
        - assignment-operator
    - include: else-pop
```

And that did fix the original problem with the prefixes. But it also broke all settings which have assignment semantics.

<img width="266" alt="image" src="https://user-images.githubusercontent.com/3646730/234134851-a8197bf8-ea4b-4036-8aca-45ce55fd97f0.png">

So this isn't quite the correct solution yet.
